version: "3.7"

services:
  web:
    build: .
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && node --inspect=0.0.0.0:9229 server.js; do sleep 2; done"
    ports:
      - "4000:4000"
      - "9229:9229"
    volumes:
      - scan-tmp:/tmp/scans
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    user: mongodb
    ports:
      - "27017:27017"

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web

volumes:
  scan-tmp: