name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main", "master", "feature/security-pipeline" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Escaneo de Secretos con Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true 

    # --- AQUÍ INICIA EL NUEVO BLOQUE SAST (CodeQL) ---
    - name: Inicializar CodeQL (SAST)
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript' # NodeGoat usa JavaScript

    - name: Auto-compilación de CodeQL
      uses: github/codeql-action/autobuild@v3

    - name: Ejecutar Análisis de CodeQL
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
    # --- AQUÍ TERMINA EL BLOQUE SAST ---

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependencias del proyecto
      run: npm install

    # Tu paso de SCA que ya funciona perfectamente:
    - name: Escaneo de dependencias con Snyk (SCA)
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
      continue-on-error: true