name: CI-Polaris-Basic
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  security-events: write

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Source
      uses: actions/checkout@v
    # For compiled languages, uncomment and configure the build setup step below:
    # - name: Setup Java JDK
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: 21
    #     distribution: temurin
    #     cache: maven
    - name: Polaris Scan
      uses: LanceMcCarthy/black-duck-security-scan@lance/update-runner-node-version
      with:
        ### SCANNING: Required fields
        polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_assessment_types: "SCA"
        
        ### SCANNING OPTIONAL
        polaris_application_name: quickstart-${{ github.event.repository.name }}
        
        ### SCANNING OPTIONAL: Pull Request comments
        polaris_prComment_enabled: true
        
        ### SCANNING OPTIONAL: GitHub Issues
        polaris_externalIssues_create: true

        ### SCANNING OPTIONAL: Fix Pull Requests
        polaris_fixpr_enabled: true

        ### GITHUB Token
        # Required when Pull Request comments, Fix Pull Requests or GitHub issues are enabled
        github_token: ${{ secrets.GITHUB_TOKEN }}

        ### ENABLE OPTIONAL SCAN REPORTS
        polaris_reports_sarif_create: true
        polaris_upload_sarif_report: true
        
        ### COVERITY BUILD COMMANDS (uncomment and configure for compiled languages)
        # coverity_build_command: mvn -B -DskipTests package
        # coverity_clean_command: mvn -B clean
        
        ### OPTIONAL DIAGNOSTICS: Upload logs as build artifact if true
        include_diagnostics: false